### ISSUE TITLE
About leap.tool

### ISSUE THREAD

**Issue by yqrzzz** [SeanChenxy/HandAvatar#1]
Hi, thank you for sharing great work.
I have successfully run the segment code and placed the pre-trained model in the correct location.But when I run the command './handavatar/scripts/run_hand.sh' to get the result, I get an error saying 'No module named 'leap.tools'. Could you help me solve this problem? Thank you!

**Comment by zxz267** [comment]
This [repository](https://github.com/neuralbodies/leap) might help you.

**Comment by zxz267** [comment]
> Hi, thank you for sharing great work. I have successfully run the segment code and placed the pre-trained model in the correct location.But when I run the command './handavatar/scripts/run_hand.sh' to get the result, I get an error saying 'No module named 'leap.tools'. Could you help me solve this problem? Thank you!

This [repository](https://github.com/neuralbodies/leap) might help you.

**Comment by relh** [comment]
This worked for me! I think this should be added as a requirement to the README too.

**Comment by therealron** [comment]
Can you elaborate how exactly you solved this? I'm getting an error regarding 
from .mise import MISE
ModuleNotFoundeError: No module named leap.tools.libmise.mise

**Comment by relh** [comment]
I just installed the leap package from that repo.
