### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by wyr718** [SeanChenxy/HandAvatar#4]
When I run the pre-train model I find it is for test_Capture0_ROM04_RT_Occlusion. May I ask what exactly the part is  in the Interhand dataset(like partaa partab ...) Cause it is so big and I am not able to load the whole dataset. Another thing is which annotation is used H+M, H or M.

**Comment by SeanChenxy** [comment]
Hi, if you only wan to run inference, you do not need to download InterHand dataset. And, you should change the code not to read GT images. If you want ot run training, you should download all `tar` (including all `part**`), and use `unzip.sh` for decompression.

**Comment by wyr718** [comment]
Thanks a lot! But how should I change the code not to read GT images? I have downloaded the whole dataset and run inference without changing code not to read GT images. It also gives out some results, is it right?

**Comment by SeanChenxy** [comment]
Yes. If you have already downloaded the dataset, there is no need to change the code.
