### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by Sweetest316** [SeanChenxy/HandAvatar#5]
Hello author, when I downloaded the dataset, I saw two datasets on the website:
(1)InterHand2.6M in 5 fps
(2)InterHand2.6M in 30 fps
May I ask which dataset you are using?
(There is a significant difference between the two datasets.)
![image](https://github.com/SeanChenxy/HandAvatar/assets/87267028/264de4a8-ba4a-460f-b942-4e03230f7c14)

![image](https://github.com/SeanChenxy/HandAvatar/assets/87267028/9c8e2b91-55ed-4bcb-ae33-21ae2b86062f)

**Comment by SeanChenxy** [comment]
Hi, `5 fps` is required
